export interface Transaction {
  receiptId: string;
  transactionAt: number;
  type: string;
  value: number;
  paymentCurrency: string;
  transactionId: string;

  [x: string]: any;
}

const transactions: Transaction[] = [
  {
    transactionId: 'e9e72d73-aa28-4aeb-8e54-787494835822',
    createdAt: 1570462971760,
    currency: 'EUR',
    paymentMethod: 'TRANSFER',
    paymentProvider: 'TREEZOR',
    providerTransactionId: 'payout_1234',
    receiptId: '',
    status: 'PENDING',
    title: 'Cotisations URSSAF',
    titleLatinised: 'cotisations urssaf',
    type: 'payout',
    uid: '297c56af-5ec9-4994-97c0-70e9c3fb6af2',
    updatedAt: 1570462971760,
    value: 165,
    bankTransferId: '',
    transactionAt: 1570462971306,
    fee: 0,
    invoiceId: '',
    transferPayinSenderName: '',
    feeType: 'FREE',
    description: '',
    category: 'DEFAULT',
    isRefund: false,
    directDebitMandateId: '',
    bankAccountId: 'd3bce33b-8a0d-4c46-b898-cbf4214a1bea',
    transactionSettledAt: 1570462971306,
    providerCardPaymentId: null,
    providerCardTransactionId: null,
    cardPaymentStatus: null,
    isPersonal: false,
    hasReceipts: false,
    note: '',
    isHidden: false,
    authorizationReleasedAt: null,
    refundTransactionId: null,
    executedAt: null,
    remainingAuthorized: null,
    expectedReleaseDate: null,
    cardPaymentMethod: null,
    paymentCurrency: 'EUR',
  },
  {
    transactionId: '595cff76-40bd-4499-98b6-e34ba858df64',
    createdAt: 1570462971105,
    currency: 'EUR',
    paymentMethod: 'CARD',
    paymentProvider: 'TREEZOR',
    providerTransactionId: 'payout_1234',
    receiptId: '',
    status: 'VALIDATED',
    title: 'Kapten',
    titleLatinised: 'kapten',
    type: 'payout',
    uid: '297c56af-5ec9-4994-97c0-70e9c3fb6af2',
    updatedAt: 1570462971105,
    value: 37,
    bankTransferId: '',
    transactionAt: 1570462970724,
    fee: 0,
    invoiceId: '',
    transferPayinSenderName: '',
    feeType: 'FREE',
    description: '',
    category: 'TRANSPORTATION',
    isRefund: false,
    directDebitMandateId: '',
    bankAccountId: 'd3bce33b-8a0d-4c46-b898-cbf4214a1bea',
    transactionSettledAt: 1570462970724,
    providerCardPaymentId: null,
    providerCardTransactionId: null,
    cardPaymentStatus: 'SETTLED',
    isPersonal: false,
    hasReceipts: false,
    note: '',
    isHidden: false,
    authorizationReleasedAt: null,
    refundTransactionId: null,
    executedAt: null,
    remainingAuthorized: null,
    expectedReleaseDate: null,
    cardPaymentMethod: null,
    paymentCurrency: 'EUR',
  },
  {
    transactionId: 'eed9b76c-0108-416f-92f8-efa7235057fa',
    createdAt: 1570462970498,
    currency: 'EUR',
    paymentMethod: 'CARD',
    paymentProvider: 'TREEZOR',
    providerTransactionId: 'payout_1234',
    receiptId: '1234',
    status: 'VALIDATED',
    title: "Mc Donald's PARIS 15",
    titleLatinised: "mc donald's paris 15",
    type: 'payout',
    uid: '297c56af-5ec9-4994-97c0-70e9c3fb6af2',
    updatedAt: 1570462970498,
    value: 12.75,
    bankTransferId: '',
    transactionAt: 1570462970045,
    fee: 0,
    invoiceId: '',
    transferPayinSenderName: '',
    feeType: 'FREE',
    description: '',
    category: 'FOOD',
    isRefund: false,
    directDebitMandateId: '',
    bankAccountId: 'd3bce33b-8a0d-4c46-b898-cbf4214a1bea',
    transactionSettledAt: 1570462970045,
    providerCardPaymentId: null,
    providerCardTransactionId: null,
    cardPaymentStatus: 'SETTLED',
    isPersonal: true,
    hasReceipts: false,
    note: '',
    isHidden: false,
    authorizationReleasedAt: null,
    refundTransactionId: null,
    executedAt: null,
    remainingAuthorized: null,
    expectedReleaseDate: null,
    cardPaymentMethod: null,
    paymentCurrency: 'EUR',
  },
  {
    transactionId: '6b97e7ac-48db-4598-8a04-3295552316d3',
    createdAt: 1570462983149,
    currency: 'EUR',
    paymentMethod: 'CARD',
    paymentProvider: 'TREEZOR',
    providerTransactionId: 'payin_544099',
    receiptId: '',
    status: 'VALIDATED',
    title: 'Google',
    titleLatinised: 'google',
    type: 'payin',
    uid: '297c56af-5ec9-4994-97c0-70e9c3fb6af2',
    updatedAt: 1570462983149,
    value: 22001.25,
    bankTransferId: '',
    transactionAt: 1570462970000,
    fee: 0,
    invoiceId: '',
    transferPayinSenderName: '',
    feeType: 'FREE',
    description: '',
    category: 'DEFAULT',
    isRefund: false,
    directDebitMandateId: '',
    bankAccountId: 'd3bce33b-8a0d-4c46-b898-cbf4214a1bea',
    transactionSettledAt: 1570462970000,
    providerCardPaymentId: null,
    providerCardTransactionId: null,
    cardPaymentStatus: null,
    isPersonal: false,
    hasReceipts: false,
    note: '',
    isHidden: false,
    authorizationReleasedAt: null,
    refundTransactionId: null,
    executedAt: null,
    remainingAuthorized: null,
    expectedReleaseDate: null,
    cardPaymentMethod: null,
    paymentCurrency: 'EUR',
  },
  {
    transactionId: '9acf350d-fceb-4b12-983c-6e02fbd60534',
    createdAt: 1470462981135,
    currency: 'EUR',
    paymentMethod: 'CARD',
    paymentProvider: 'TREEZOR',
    providerTransactionId: 'payin_544100',
    receiptId: '',
    status: 'VALIDATED',
    title: 'Trainline',
    titleLatinised: 'trainline',
    type: 'payin',
    uid: '297c56af-5ec9-4994-97c0-70e9c3fb6af2',
    updatedAt: 1570462981135,
    value: 121.25,
    bankTransferId: '',
    transactionAt: 1570361970000,
    fee: 0,
    invoiceId: '',
    transferPayinSenderName: '',
    feeType: 'FREE',
    description: '',
    category: 'DEFAULT',
    isRefund: false,
    directDebitMandateId: '',
    bankAccountId: 'd3bce33b-8a0d-4c46-b898-cbf4214a1bea',
    transactionSettledAt: 1570462970000,
    providerCardPaymentId: null,
    providerCardTransactionId: null,
    cardPaymentStatus: null,
    isPersonal: false,
    hasReceipts: false,
    note: '',
    isHidden: false,
    authorizationReleasedAt: null,
    refundTransactionId: null,
    executedAt: null,
    remainingAuthorized: null,
    expectedReleaseDate: null,
    cardPaymentMethod: null,
    paymentCurrency: 'EUR',
  },
];

export default transactions;
